version: '3.8'

services:
  assassin-bot:
    build: .
    container_name: assassin_bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=YOUR_DISCORD_BOT_TOKEN  # Pass your bot token here if you prefer
    volumes:
      - .:/app
